import type { Metadata } from 'next';
import { Manrope, Inter, Instrument_Sans } from 'next/font/google';
import './globals.css';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const instrumentSans = Instrument_Sans({
  variable: '--font-instrumentSans',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Imotech Digital | Modern Web Solution for Growing Brands',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${manrope.variable} ${instrumentSans.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
